/**************************************************************************
 Skarynka - software for scan, process scanned images and build books

 Copyright (C) 2016 Aleś Bułojčyk

 This file is part of Skarynka.

 Skarynka is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Skarynka is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/
package org.alex73.skarynka.scan.ui.book;

/**
 *
 * @author Aleś Bułojčyk <alex73mail@gmail.com>
 */
public class PanelEdit extends javax.swing.JPanel {

    /**
     * Creates new form PanelEdit
     */
    public PanelEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        pagesScrollBar = new javax.swing.JScrollPane();
        pagesPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        previewOrig = new javax.swing.JToggleButton();
        previewFull = new javax.swing.JToggleButton();
        previewInc = new javax.swing.JButton();
        previewDec = new javax.swing.JButton();
        previewTags = new javax.swing.JLabel();
        scrollPreview = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setResizeWeight(0.5);

        pagesScrollBar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pagesPanel.setLayout(new java.awt.GridLayout(0, 5, 10, 10));
        pagesScrollBar.setViewportView(pagesPanel);

        jSplitPane1.setLeftComponent(pagesScrollBar);

        jPanel1.setLayout(new java.awt.BorderLayout());

        buttonGroup1.add(previewOrig);
        previewOrig.setText("1:1");
        jPanel2.add(previewOrig);

        buttonGroup1.add(previewFull);
        previewFull.setText("#");
        jPanel2.add(previewFull);

        previewInc.setText("+");
        jPanel2.add(previewInc);

        previewDec.setText("-");
        jPanel2.add(previewDec);

        previewTags.setText("[]");
        jPanel2.add(previewTags);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);
        jPanel1.add(scrollPreview, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JPanel pagesPanel;
    public javax.swing.JScrollPane pagesScrollBar;
    public javax.swing.JButton previewDec;
    public javax.swing.JToggleButton previewFull;
    public javax.swing.JButton previewInc;
    public javax.swing.JToggleButton previewOrig;
    public javax.swing.JLabel previewTags;
    public javax.swing.JScrollPane scrollPreview;
    // End of variables declaration//GEN-END:variables
}
