/**************************************************************************
 Skarynka - software for scan, process scanned images and build books

 Copyright (C) 2016 Aleś Bułojčyk

 This file is part of Skarynka.

 Skarynka is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Skarynka is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/
package org.alex73.skarynka.scan.ui.scan;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

import org.alex73.skarynka.scan.Messages;
import org.alex73.skarynka.scan.ui.TagsPanel;

/**
 * @author Aleś Bułojčyk <alex73mail@gmail.com>
 */
public class ScanControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScanControlPanel
     */
    public ScanControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        btnSkip = new JToggleButton();
        btnNumber = new JButton();
        jPanel1 = new JPanel();
        txtNumber = new JTextField();
        labelInfo = new JLabel();
        tags = new TagsPanel();

        setLayout(new GridBagLayout());

        btnSkip.setText(Messages.getString("SCAN_CONTROL_DISABLE")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new Insets(3, 3, 0, 3);
        add(btnSkip, gridBagConstraints);

        btnNumber.setText(Messages.getString("SCAN_CONTROL_CHANGE_NUMBER")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new Insets(3, 3, 0, 3);
        add(btnNumber, gridBagConstraints);

        jPanel1.setLayout(new BorderLayout());

        txtNumber.setColumns(6);
        jPanel1.add(txtNumber, BorderLayout.CENTER);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(3, 3, 0, 3);
        add(jPanel1, gridBagConstraints);

        labelInfo.setText(Messages.getString("CAMERA_INFO")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(3, 3, 0, 3);
        add(labelInfo, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        add(tags, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnNumber;
    public JToggleButton btnSkip;
    public JPanel jPanel1;
    public JLabel labelInfo;
    public TagsPanel tags;
    public JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
